# Generated by Django 3.2.4 on 2021-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20210630_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2021-06-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organiser_email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
